version: '3.1'

services:
  database:
    image: mysql       
    container_name: databasemysql
    ports:
        - "3306:3306"        
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}