version: '3.1'

services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo
    hostname: ${MONGO_HOSTNAME}
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
